//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace watersaver.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tip
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [DisplayName("Short Description")]
        public string Addition { get; set; }
    }
}
